_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  # META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  RPN:
    IN_FEATURES: ["vgg4"]
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 1
    IN_FEATURES: ["vgg4"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (30000, 40000, 45000, 180000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 50000
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.005
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("DIOR_train",)
  TRAIN_UNLABEL: ("SSDD_train",)
  TEST: ("SSDD_test",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 10000
  BURN_UP_STEP: 1
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 1000
